language: python
python:
- 3.6
install:
- pip install -U tox tox-travis codecov
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: andreycizov
  password:
    secure: Y/TREH8xE0fgkO5+EpwrXHOuCLy6uWXu9qBrljhnV2B2gtHt0zMxZ6eHfoiysothk2DU7evBmd3OMPXruPPlnJstICLAdX0ufihWEQjfITPkOzv9dPFhbFDshFNIkbE8nuG10C1RPueIVpizt1aY7tCJBO0i7Qnxt7/l89S8e2aMHu+QRXzMZI+MMed+ZTHJ/A8gMVtSMmVFb6+a1Idp3khysNRrCkBJij+vdZkanc5+oZAVyBJBFgt7q2gQar+6Wr3yzLg95/rDkXxPTT+/VEKOVHRlW4bPDEcikJbzBhVPk/5bO6dp02zeLs3qVqomQqGr/bXUtnTlB3gwsW12+7BZYRjkxZUUS+xqQeaVJ6x6YBfK/BucLnqxIyMFaIYlpXCbmefXDGxPU2GWl0DBKYHXptKNHqpgW9jhPvIphn9IXTA8dnCp/Ah3dPhzk9IBsNjURsgRY2FphUsVkaVw6j9dnMSngM0Y28T8XCNFQl5QQbw8eWl95spE5FqRK6AJBXVTcGv3NylBdjhI3RzRxPKIZuVWGkzTFQqHL+q28nGJ80ZnABwd0zx9+Mh2X/dvMLZd0KKqJIWQVqVbk90J9elZD1BahwtaMZ7eK7GfSqTyebLnXOy0HJpfx6rj9lMbBLk8DhfVURDbKT3vNLxvhfqEP+Y7m0egd9c2VZpVWr0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: andreycizov/python-xmake
